name: task_manager_pro
description: "Do an mon lap trinh tren thiet bi di dong"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core packages
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.0.5

  cupertino_icons: ^1.0.8

  fl_chart: ^0.68.0

  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
