// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbT_9XlqWjRVSt_MHXqNU3Sh6eTDLD_Ok',
    appId: '1:1051661515863:web:c632788e1dae1b475d7712',
    messagingSenderId: '1051661515863',
    projectId: 'mquang-ce72a',
    authDomain: 'mquang-ce72a.firebaseapp.com',
    databaseURL: 'https://mquang-ce72a-default-rtdb.firebaseio.com',
    storageBucket: 'mquang-ce72a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9uV7qvSb7-0O642Ctlol1qAcGT5tS34Q',
    appId: '1:1051661515863:android:437eeb916c5a0f275d7712',
    messagingSenderId: '1051661515863',
    projectId: 'mquang-ce72a',
    databaseURL: 'https://mquang-ce72a-default-rtdb.firebaseio.com',
    storageBucket: 'mquang-ce72a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0a0ScYSXObZ6vxCYuFdjI3at3zOLcDY',
    appId: '1:1051661515863:ios:7a96b46b6b54e5fb5d7712',
    messagingSenderId: '1051661515863',
    projectId: 'mquang-ce72a',
    databaseURL: 'https://mquang-ce72a-default-rtdb.firebaseio.com',
    storageBucket: 'mquang-ce72a.firebasestorage.app',
    iosBundleId: 'com.example.doanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0a0ScYSXObZ6vxCYuFdjI3at3zOLcDY',
    appId: '1:1051661515863:ios:7a96b46b6b54e5fb5d7712',
    messagingSenderId: '1051661515863',
    projectId: 'mquang-ce72a',
    databaseURL: 'https://mquang-ce72a-default-rtdb.firebaseio.com',
    storageBucket: 'mquang-ce72a.firebasestorage.app',
    iosBundleId: 'com.example.doanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbT_9XlqWjRVSt_MHXqNU3Sh6eTDLD_Ok',
    appId: '1:1051661515863:web:0efe27730d1209b35d7712',
    messagingSenderId: '1051661515863',
    projectId: 'mquang-ce72a',
    authDomain: 'mquang-ce72a.firebaseapp.com',
    databaseURL: 'https://mquang-ce72a-default-rtdb.firebaseio.com',
    storageBucket: 'mquang-ce72a.firebasestorage.app',
  );

}